local M = {
  "oxfist/night-owl.nvim",
  name = "night-owl",
  priority = 1000,
  lazy = false,
}

function M.config()
  require("night-owl").setup({
    transparent = false,
    italic_comments = true,
    bold_functions = true,
    bold_keywords = true,
    bold_conditionals = true,
    bold_operators = false,
    bold_variables = false,
    bold_numbers = false,
    bold_booleans = false,
    bold_parameters = false,
    italic_functions = false,
    italic_variables = false,
    italic_keywords = false,
    italic_conditionals = false,
    italic_operators = false,
    italic_numbers = false,
    italic_booleans = false,
    italic_parameters = false,
    bold_italic_functions = false,
    bold_italic_variables = false,
    bold_italic_keywords = false,
    bold_italic_conditionals = false,
    bold_italic_operators = false,
    bold_italic_numbers = false,
    bold_italic_booleans = false,
    bold_italic_parameters = false,
    underline_functions = false,
    underline_variables = false,
    underline_keywords = false,
    underline_conditionals = false,
    underline_operators = false,
    underline_numbers = false,
    underline_booleans = false,
    underline_parameters = false,
    italic_strings = false,
    bold_strings = false,
    bold_italic_strings = false,
    underline_strings = false,
    italic_comments = true,
    bold_comments = false,
    bold_italic_comments = false,
    underline_comments = false,
    italic_loops = false,
    bold_loops = false,
    bold_italic_loops = false,
    underline_loops = false,
    italic_regex = false,
    bold_regex = false,
    bold_italic_regex = false,
    underline_regex = false,
    italic_escapes = false,
    bold_escapes = false,
    bold_italic_escapes = false,
    underline_escapes = false,
    italic_symbols = false,
    bold_symbols = false,
    bold_italic_symbols = false,
    underline_symbols = false,
    italic_fields = false,
    bold_fields = false,
    bold_italic_fields = false,
    underline_fields = false,
  })

  vim.cmd.colorscheme "night-owl"
end

return M
